### ISSUE TITLE
Is install-local.py deprecated?

### ISSUE THREAD

**Issue by wwuck** [pre-commit/pre-commit.com#596]
Hi,

I was setting up a new desktop today and noticed that `install-local.py` no longer appears on pre-commit.com install docs.  Has this install method been deprecated?  I did find the commit removing it from the website but I couldn't find any associated bug report.

**Comment by asottile** [comment]
yes. this was briefly discussed here: https://github.com/pre-commit/pre-commit.com/issues/584#issuecomment-972972571

while convenient, install-local depended on an ageing version of `virtualenv` and a non-portable installation approach (symlinks)

if you want a more direct replacement -- I would suggest writing a small script utilizing the virtualenv zipapp -- something similar to:

```
curl --silent --location -o virtualenv.pyz https://bootstrap.pypa.io/virtualenv.pyz
python3 virtualenv.pyz ~/.pre-commit-venv
~/.pre-commit-venv/bin/pip install pre-commit
ln -s ~/.pre-commit-venv/bin/pre-commit ~/bin/pre-commit
```

this also gives you a lot more control over how and where you install things (rather than the specialized `install-local.py` needing to have more features to take on that complexity to support custom installation schemes)
