### ISSUE TITLE
If possible, please remove stackoverflow from https://pre-commit.com/#getting-help

### ISSUE THREAD

**Issue by honey-speaks-tech** [pre-commit/pre-commit.com#895]
Hi all,

I have a very bad experience asking a query related to pre-commit in stackoverflow as mentioned in [Getting-help]( https://pre-commit.com/#getting-help). Almost spoiled two hours of my productive working time. 

This is my humble proposal, to remove `stackoverflow` link from `Getting help` section. 
If you don't agree, no problem at all. But I just want to notify this here.

Please see the discussions in stack-overflow happened:

- [See the corrections done by stackoverflow moderators for my original precommit post](https://stackoverflow.com/posts/77431214/revisions)

- [Post in meta.stackoverflow.com](https://meta.stackoverflow.com/questions/427086/why-are-posts-to-be-allowed-to-downvoted-without-telling-the-reason-why-it-is-do?noredirect=1#comment977290_427086)

Thank you in advance,
Honey

Honey Sukesan (She / Her)

**Comment by asottile** [comment]
you had a poor experience because you didn't follow stackoverflow's guidelines -- you asked a poor question which was just asking for software recommendations which is off topic on stack overflow.  stackoverflow is fine for asking technical Q&A and there are many on-topic questions on stackoverflow for [pre-commit.com] -- yours was very much not.

you also asked this in two other places -- be patient and ask in only one place

**Comment by asottile** [comment]
and to be fair to your meta question I was the downvoter *and* I did leave a reason as a close vote
